# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d50577d59e83603912be641a6b8073154d6ec6d831b3e83044644671cad61d4bc9dd74909f7c577808bb3ff3d44ddb28a8d1f3335602b38c218a903762ecb74

test:
  secret_key_base: 28078a47bf2d49427c284bcbe5e339c7e0f8ce677d0874507b0c42e64cbd85472c397622fe51b6dc7084a363429ba39d6fd85e639452756ac71977280c08e362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
